server:
      port: 8080
spring:
      application:
            name: Database Modeling Tool
      config:
            import: "file:.env[.properties]"
      h2:
            console:
                  enabled: true
                  path: /h2-console
      datasource:
            generate-unique-name: false
            name: lab1
            url: jdbc:h2:mem:lab1
            driver-class-name: org.h2.Driver
            username: "${DB_USERNAME}"
            password: "${DB_PASSWORD}"
      jpa:
            hibernate:
                  ddl-auto: create
